#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop

# Initialize the counter
count=1

# Start the while loop
while [ $count -le 10 ]
do
    echo "Best School"
    # Increment the counter
    ((count++))
done
