#!/usr/bin/env bash
# Loop from 1 to 10, printing specific messages for 4 and 8,
# and "Best School" for others.

count=1

while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    
    # Increment the counter
    ((count++))
done
