#!/usr/bin/env bash
# Script to check existence, size, and type of a file named 'school'

FILE="school"

# Check for existence
if [ -e "$FILE" ]; then
    echo "$FILE file exists"

    # If file exists, check if it is empty
    if [ -s "$FILE" ]; then
        echo "$FILE file is not empty"
    else
        echo "$FILE file is empty"
    fi

    # Check if it is a regular file
    if [ -f "$FILE" ]; then
        echo "$FILE is a regular file"
    fi

else
    echo "$FILE file does not exist"
fi
